# scripts/deck-audio.py — the `deckAudio` card: an OPTIONAL voiceover for a built deck.
#
# Headless twin of OpenDeck's in-browser Audio Studio (deck-narration.js). It reads
# the deck's speaker notes, asks ElevenLabs for one clip per slide, and writes the
# two files the Studio would have produced — narration-script.js (the text) and
# narration-audio.js (the baked clips, `window.__NARRATION_AUDIO`) — then wires the
# narration scripts into deck/deck.html so the bundler inlines them like any other
# script. The request shape mirrors deck-narration.js so a clip generated here and
# one generated in the Studio are interchangeable.
#
# Runs ONLY when the Clarify answers ask for it AND a key and a voice id are
# available; otherwise it passes with a "skipped" report, which is the default and
# the unattended-without-a-key case. It never fails a run for lack of audio, and the
# API key is read from the environment and NEVER written to a file, a report or a log.
#
# Standard library only (must parse on python 3.8). stdout is protocol-reserved.
import base64
import json
import os
import re
import shutil
import urllib.error
import urllib.request

API_BASE = 'https://api.elevenlabs.io'
DEFAULT_MODEL = 'eleven_multilingual_v2'
# The env vars the key may arrive in, most specific first. The first is what the
# engine sets when a user TYPES a key into the Ask card (held in memory, never
# stored); the second is the ordinary place a key already lives.
KEY_ENV = ('WORCA_DECK_ELEVENLABS_API_KEY', 'ELEVENLABS_API_KEY')
VOICE_ENV = ('WORCA_DECK_ELEVENLABS_VOICE_ID', 'ELEVENLABS_VOICE_ID')

NARRATION_TAGS = (
    '<script src="narration-script.js"></script>\n'
    '<script src="narration-audio.js"></script>\n'
    '<script src="deck-narration.js"></script>\n'
)
NOTES_RE = re.compile(
    r'<script\b[^>]*\bid\s*=\s*["\']?speaker-notes["\']?[^>]*>(.*?)</script\s*>', re.I | re.S)


def first_env(names):
    for n in names:
        v = os.environ.get(n)
        if v and v.strip():
            return v.strip()
    return ''


def read_json(path):
    try:
        with open(path, encoding='utf-8') as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def answers_path(api):
    """deck-outputs.json in the pipeline dir: the deckOutputs answers. Read by path rather than
    through a wire (see presentation-workflow.mjs w37) — and the barrier on the builder guarantees
    it is final by the time any optional card runs."""
    return os.path.join(api.ctx.pipelineDir, 'deck-outputs.json')


def wants_audio(answers):
    """True only when the Clarify answers explicitly select narration audio.

    The answers file is the clarifier's: a list of question records whose answer is
    folded in, or a flat `values` map from a form. Anything unreadable is "no" — the
    default is a silent deck, never an accidental spend."""
    if not answers:
        return False
    values = answers.get('values') if isinstance(answers, dict) else None
    if isinstance(values, dict):
        return str(values.get('audio', '')).lower().startswith('generate')
    qs = answers.get('questions') if isinstance(answers, dict) else None
    for q in qs or []:
        if isinstance(q, dict) and q.get('id') == 'audio':
            a = q.get('answer')
            return isinstance(a, str) and a.lower().startswith('generate')
    return False


def answer_voice(answers):
    if isinstance(answers, dict):
        values = answers.get('values')
        if isinstance(values, dict) and isinstance(values.get('voiceId'), str):
            return values['voiceId'].strip()
    return ''


def read_notes(deck_html):
    """The deck's own speaker notes — one string per slide, '' for none."""
    m = NOTES_RE.search(deck_html)
    if not m:
        return []
    try:
        data = json.loads(m.group(1).strip() or '[]')
    except ValueError:
        return []
    if isinstance(data, dict):
        data = data.get('notes', [])
    return [n.strip() if isinstance(n, str) else '' for n in data] if isinstance(data, list) else []


def script_js(voice_id, model_id, notes):
    doc = {'voiceId': voice_id, 'modelId': model_id, 'gapSeconds': 0.5,
           'slides': [{'lines': [n]} for n in notes]}
    return ('/* Generated by the deckAudio card from the deck\'s speaker notes. */\n'
            'window.__NARRATION = ' + json.dumps(doc, ensure_ascii=False, indent=1) + ';\n')


def tts(base, key, voice_id, model_id, text):
    url = '%s/v1/text-to-speech/%s?output_format=mp3_44100_128' % (base, urllib.request.quote(voice_id, safe=''))
    body = json.dumps({'text': text, 'model_id': model_id,
                       'voice_settings': {'stability': 0.5, 'similarity_boost': 0.75,
                                          'style': 0.0, 'use_speaker_boost': True}}).encode('utf-8')
    req = urllib.request.Request(url, data=body, method='POST', headers={
        'xi-api-key': key, 'Content-Type': 'application/json', 'Accept': 'audio/mpeg'})
    with urllib.request.urlopen(req, timeout=120) as res:
        return res.read()


def wire_deck(html):
    """Add the narration scripts to deck.html once, after the last kit script."""
    if 'narration-audio.js' in html and 'deck-narration.js' in html:
        return html, False
    # Drop a commented-out placeholder for the audio tag if the template carried one.
    html = html.replace('<!-- <script src="narration-audio.js"></script> -->', '')
    idx = html.lower().rfind('</body>')
    if idx < 0:
        return html + '\n' + NARRATION_TAGS, True
    return html[:idx] + NARRATION_TAGS + html[idx:], True


def write_report(api, lines, issues, summary):
    body = '\n'.join(['# Deck audio', ''] + lines + ['']) + '\n'
    # `report` and `findings` share one filename, so one write satisfies whichever way the verdict goes.
    for port in ('report', 'findings'):
        p = api.outputs.get(port) if hasattr(api.outputs, 'get') else None
        path = p.get('path') if p else None
        if path:
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(body)
    return {'verdict': {'issues': issues, 'summary': summary}, 'summary': summary}


def main(api):
    pdir = api.ctx.pipelineDir
    answers = read_json(answers_path(api))

    if not wants_audio(answers):
        return write_report(api, ['Skipped: narration audio was not requested (the default).'], [],
                            'audio skipped (not requested)')

    key = first_env(KEY_ENV)
    voice = answer_voice(answers) or first_env(VOICE_ENV)
    if not key or not voice:
        missing = ' and '.join(x for x, v in (('an ElevenLabs API key', key), ('a voice id', voice)) if not v)
        return write_report(api, ['Skipped: narration audio was requested but %s is not available.' % missing,
                                  'Set ELEVENLABS_API_KEY / ELEVENLABS_VOICE_ID, or answer the audio question '
                                  'in an attended run. The deck ships without a voiceover.'], [],
                            'audio skipped (no key or voice)')

    deck_dir = os.path.join(pdir, 'deck')
    deck_path = os.path.join(deck_dir, 'deck.html')
    if not os.path.isfile(deck_path):
        return write_report(api, ['No deck to narrate.'], [{
            'severity': 'critical', 'title': 'No deck to narrate',
            'detail': 'deck/deck.html does not exist in the pipeline directory.',
            'location': 'deck/deck.html'}], 'no deck')
    with open(deck_path, encoding='utf-8', errors='replace') as fh:
        html = fh.read()

    notes = read_notes(html)
    if not any(notes):
        return write_report(api, ['Skipped: the deck has no speaker notes to narrate.'], [],
                            'audio skipped (no speaker notes)')

    engine = os.path.join(pdir, 'deck-narration', 'deck-narration.js')
    if not os.path.isfile(engine):
        return write_report(api, ['deck-narration/deck-narration.js was not staged.'], [{
            'severity': 'major', 'title': 'Narration engine missing',
            'detail': 'The audio step declares requiresAssets: ["deck-narration"] but it was not staged.',
            'location': 'deck-narration/'}], 'narration engine missing')

    base = (os.environ.get('WORCA_DECK_ELEVENLABS_BASE') or API_BASE).rstrip('/')
    model = DEFAULT_MODEL
    clips = {}
    failed = []
    for si, text in enumerate(notes):
        if not text:
            continue
        try:
            audio = tts(base, key, voice, model, text)
            clips['%d:0' % si] = 'data:audio/mpeg;base64,' + base64.b64encode(audio).decode('ascii')
        except urllib.error.HTTPError as e:
            # The body of an auth failure can echo request details; report the status only.
            failed.append((si + 1, 'HTTP %d' % e.code))
        except (urllib.error.URLError, OSError) as e:
            failed.append((si + 1, type(e).__name__))

    issues = []
    if failed and not clips:
        issues.append({'severity': 'major', 'title': 'No narration could be generated',
                       'detail': 'Every clip failed (%s). Check the API key and voice id.' % failed[0][1],
                       'location': 'deck/narration-audio.js'})
        return write_report(api, ['Audio requested; generation failed for every slide.'], issues,
                            'audio failed')

    with open(os.path.join(deck_dir, 'narration-script.js'), 'w', encoding='utf-8') as fh:
        fh.write(script_js(voice, model, notes))
    with open(os.path.join(deck_dir, 'narration-audio.js'), 'w', encoding='utf-8') as fh:
        fh.write('/* Generated narration audio. voice=%s */\nwindow.__NARRATION_AUDIO = %s;\n'
                 % (voice, json.dumps(clips)))
    shutil.copyfile(engine, os.path.join(deck_dir, 'deck-narration.js'))
    html2, changed = wire_deck(html)
    if changed:
        with open(deck_path, 'w', encoding='utf-8') as fh:
            fh.write(html2)

    lines = ['Generated %d clip(s) for %d slide(s) with voice `%s`.' % (len(clips), len(notes), voice),
             'Wrote deck/narration-script.js, deck/narration-audio.js and deck/deck-narration.js; '
             'deck/deck.html now loads them.']
    if failed:
        lines.append('Clips that failed (slide: reason): ' + ', '.join('%d: %s' % f for f in failed)
                     + ' — those slides play silently.')
    return write_report(api, lines, issues, 'audio: %d clip(s)' % len(clips))
